id: A6AA8A699
title: Prayer to the Lineage of Vajra Akṣobhya
type: translation
pechas:
- IE88DD88D
- I582078A2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:57:07.537583
  last_modified_at: 2023-01-04 11:57:07.537586
  collections:
  - Getse Mahāpaṇḍita Series
  - Works of Tibetan Masters
alignment_to_base:
  IE88DD88D/A264: 80D0
  I582078A2/DA04: 80D0
